### ISSUE TITLE
Access to Self-help Resources

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/mentalhealth#2]
- [x] As a college student experiencing anxiety, I want access to self-help resources, so that I can learn strategies to cope with my anxiety on my own time.

**Acceptance Criteria:**

- [x] The website should offer a variety of self-help articles, videos, and exercises.

- [x] Resources should be categorized by specific issues like anxiety, depression, etc.

- [x] There should be downloadable guides and tools for practicing mindfulness, meditation, and other techniques.

- [x] An option to ask questions or leave feedback on resources should be included.

**tasks** 

- [x] add self help articles to do with mental health anxiety and stress

- [x] all resource should be catorgorized appropriately with heading like anxiety despression mental health well being and maybe related to specific conditions.

- [x] Add downloadable documents that include mindfulness meditation and other techqniques.

- [ ] Add a feedback form on the resources page for people to provide feedback on the available or unavailable resources.
