### ISSUE TITLE
Peer Support Community

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/mentalhealth#3]
- [x] As a parent dealing with postpartum depression, I want to connect with others going through similar experiences, so that I can share my feelings and get support from a community.

**Acceptance Criteria:**

- [x] The website should include a moderated forum or chat room for users to connect.

- [x] It should provide discussion groups for various mental health topics, including postpartum depression.

- [x] Privacy settings should be available to control the visibility of personal information.

- [x] There should be clear guidelines and active moderation to ensure a safe and supportive environment.

**tasks**

- [x] add a forum or chatbased room for user to engage, interact with each other 

- [x] it should have discussion group or board for the different topics anxiety depression stress mindfulness meditation and mental health 

- [ ] add privacy settings to control the visibility of personal information 

- [ ] Add clear rules and regulation to the forum board to ensure a safe and welcoming environment.
