### ISSUE TITLE
Crisis Support

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/mentalhealth#4]
- [x] As a teenager experiencing a mental health crisis,\ I want immediate access to crisis support,\ so that I can get help right away and ensure my safety.

**Acceptance Criteria:**

- [x] The website should prominently display emergency contact information and crisis hotline numbers.

- [ ] It should offer a live chat feature for immediate assistance.

- [x] There should be clear steps and resources for crisis situations, including contact details for local support services.

- [x] An option to speak with a mental health professional in real-time should be included.

**tasks**

- [ ] create a page with all emergency contact information and crisis hotline numbers this should be clear and obvious it where to get emergency help 

- [ ] add a live chat feature of some description where they can talk to a volunteer to protect them from harm 

- [ ] add clear steps and instruction of what to do if your experiencing a crisis.

- [ ] add an option to talk to someone in realtime.( would be found from the emergency numbers above. maybe make it clear this is the first step you need to take
