### ISSUE TITLE
Navbar for Easy Access

### ISSUE THREAD

**Issue by newworldhost** [newworldhost/mentalhealth#5]
- [x] As a user, I want a responsive and intuitive navbar so that I can easily navigate through the website.

**Acceptance Criteria:**

- [x] The navbar should be visible on all pages of the website.

- [x] It should collapse into a hamburger menu on smaller screens (like mobile devices) and expand on larger screens.

- [x] The navbar should contain links to the main sections of the website (e.g., Home, About, Services, Contact).

- [x] When a link is clicked, the user should be smoothly scrolled or navigated to the corresponding section/page.

- [x] The active link should be highlighted to indicate the current section/page.

**tasks**

- [x] create a navbar on all pages of the website 

- [x] make it responsive on smaller screem 

- [x] make sure it has the relvant section home about services contact 

- [x] make sure smooth scrolling behaviour is used. 

- [x] make sure active class is used on active page
